# Generated by Django 2.1.2 on 2018-11-03 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ('datetime',)},
        ),
        migrations.AddField(
            model_name='talkattendance',
            name='timeslot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.TimeSlot'),
            preserve_default=False,
        ),
    ]
