# Generated by Django 2.1.2 on 2018-10-29 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='external_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='talk',
            name='external_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
