# Generated by Django 2.1.2 on 2018-11-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181103_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkattendance',
            name='modofied',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
