# Generated by Django 2.1.2 on 2018-11-09 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_talkattendance_modofied'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='sortable',
            field=models.BooleanField(default=True),
        ),
    ]
