# Generated by Django 2.1.2 on 2018-11-10 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181109_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='description',
            new_name='text',
        ),
    ]
