# Generated by Django 2.1.2 on 2019-09-08 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181110_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='conference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Conference'),
        ),
        migrations.AddField(
            model_name='room',
            name='conference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Conference'),
        ),
        migrations.AddField(
            model_name='talkattendance',
            name='conference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Conference'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='conference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Conference'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='endtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='external_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
