# Generated by Django 2.1.2 on 2019-09-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190908_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='conference',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
