# Generated by Django 2.1.2 on 2019-09-17 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190911_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='conference',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Conference'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='conference',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Conference'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='talkattendance',
            name='conference',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Conference'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='conference',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Conference'),
            preserve_default=False,
        ),
    ]
